### ISSUE TITLE
为了适配ios9需要在info.plist里面把需要访问的URL加入白名单

### ISSUE THREAD

**Issue by ultra7677** [GarveyCalvin/ApplicationJumpAndSentValue#1]
不然app会没有权限去访问URL 

比如ApplicationOne,具体做法就是在info.plist里面加入。
    <key>LSApplicationQueriesSchemes</key>
    <array>
        <string>GC</string>
    </array>

**Comment by GarveyCalvin** [comment]
HI，你是对的，要在`info.plist`里增加这些信息：

```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>GC</string>
</array>
```

在此感谢你的提醒，谢谢，已更新blog和git源码。
